-- SQLQueryHW - nextDATE.sql

USE PV_521_Import;
SET DATEFIRST 1;
GO

CREATE OR ALTER FUNCTION NextDate(@prevDate AS DATE)RETURNS DATE
AS
BEGIN
	DECLARE @day	AS TINYINT		=	DATEPART(WEEKDAY, @prevDate);
	SET @prevDate	=	DATEADD(DAY,IIF(@day = 5,3,2),@prevDate);
	RETURN @prevDate ;
END