CREATE DATABASE PV_521_ALL_IN_ONE
ON
(
	NAME		=	PV_521_ALL_IN_ONE,
	FILENAME	=	'L:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_521_ALL_IN_ONE.mdf',
	SIZE		=	  8 MB,
	MAXSIZE		=	500 MB,
	FILEGROWTH	=	  8 MB
)
LOG ON
(
	NAME		=	PV_521_ALL_IN_ONE_log,
	FILENAME	=	'L:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\PV_521_ALL_IN_ONE_log.ldf',
	SIZE		=	  8 MB,
	MAXSIZE		=	500 MB,
	FILEGROWTH	=	  8 MB
)